# Generated by Django 5.0.1 on 2025-11-27 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_key', models.CharField(blank=True, max_length=50, verbose_name='Property Key')),
                ('property_code', models.CharField(blank=True, max_length=50, verbose_name='Property Code')),
                ('neighborhood_nbr', models.CharField(blank=True, max_length=50, verbose_name='Neighborhood Number')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('sale_type_code', models.CharField(blank=True, max_length=10, verbose_name='Sale Type Code')),
                ('sale_type_desc', models.CharField(blank=True, max_length=100, verbose_name='Sale Type Description')),
                ('grantee_name', models.CharField(blank=True, max_length=255, verbose_name='Grantee Name')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sale Amount')),
                ('sale_date', models.DateTimeField(blank=True, null=True, verbose_name='Sale Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
