# Generated by Django 5.0.1 on 2025-11-27 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='File')),
                ('file_size', models.IntegerField(verbose_name='File Size (bytes)')),
                ('record_count', models.IntegerField(default=0, verbose_name='Record Count')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error')], default='uploaded', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Data Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='data_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.datafile', verbose_name='Data File'),
        ),
    ]
