# Generated by Django 5.0.1 on 2025-11-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_datafile_property_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='columns',
            field=models.JSONField(blank=True, default=list, verbose_name='Columns'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='data',
            field=models.JSONField(blank=True, default=list, verbose_name='Data'),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
